// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace SotkonTestProject.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("ControlSaleTime")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("money");

                    b.Property<long>("DropTime")
                        .HasColumnType("bigint");

                    b.Property<long>("ExistsTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDroped")
                        .HasColumnType("bit");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Bans");

                    b.HasDiscriminator<string>("BanType").HasValue("Ban");
                });

            modelBuilder.Entity("Entities.Baget", b =>
                {
                    b.HasBaseType("Entities.Ban");

                    b.HasDiscriminator().HasValue("Baget");
                });

            modelBuilder.Entity("Entities.Crendel", b =>
                {
                    b.HasBaseType("Entities.Ban");

                    b.HasDiscriminator().HasValue("Crendel");
                });

            modelBuilder.Entity("Entities.Croissant", b =>
                {
                    b.HasBaseType("Entities.Ban");

                    b.HasDiscriminator().HasValue("Croissant");
                });

            modelBuilder.Entity("Entities.Smetannik", b =>
                {
                    b.HasBaseType("Entities.Ban");

                    b.HasDiscriminator().HasValue("Smetannik");
                });
#pragma warning restore 612, 618
        }
    }
}
